#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter
#
# Complete the 'anagram' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def anagram(s):
    # Write your code here
    n = len(s)
    if n % 2 != 0:
        return -1
    half = n // 2
    s1 = s[:half]
    s2 = s[half:]
    count1 = Counter(s1)
    count2 = Counter(s2)
    changes = 0
    # Calculate the difference in counts
    for char in count2:
        if char in count1:
            if count2[char] > count1[char]:
                changes += count2[char] - count1[char]
        else:
            changes += count2[char]
    return changes

    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = anagram(s)

        fptr.write(str(result) + '\n')

    fptr.close()
