#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'closestNumbers' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def closestNumbers(arr):
    # Write your code here
    arr.sort()
    min_diff=float('inf')
    pairs=[]
    for i in range(len(arr)-1):
        current_diff=abs(arr[i+1]-arr[i])
        if current_diff<min_diff:
            min_diff=current_diff
            pairs=[(arr[i],arr[i+1])]
        elif current_diff==min_diff:
            pairs.append((arr[i],arr[i+1]))
    result=[]
    for pair in pairs:
        result.extend(pair)
    result=sorted(list(set(result)))
    return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = closestNumbers(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
