#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter
#
# Complete the 'sockMerchant' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY ar
#

def sockMerchant(n, ar):
    # Write your code here

    res=dict(Counter(ar))
    pairs=sum(v//2 for v in res.values())
    
        
    return pairs

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()



actual code

import math
import os
import random
import re
import sys
from collections import Counter
def sockMerchant(n, ar):
    res=dict(Counter(ar))
    pairs=sum(v//2 for v in res.values())  
    return pairs

