#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'flippingMatrix' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY matrix as parameter.
#

def flippingMatrix(matrix,n):
    # Write your code here
    total=0
    for i in range(n):
        for j in range(n):
            val1=matrix[i][j]
            val2=matrix[i][2*n-1-j]
            val3=matrix[2*n-1-i][j]
            val4=matrix[2*n-1-i][2*n-1-j]
            total+=max(val1,val2,val3,val4)
    return total
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        n = int(input().strip())

        matrix = []

        for _ in range(2 * n):
            matrix.append(list(map(int, input().rstrip().split())))

        result = flippingMatrix(matrix,n)

        fptr.write(str(result) + '\n')

    fptr.close()
