#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'minimumDistances' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def minimumDistances(a):
    # Write your code here
    index={}
    min_dict=float('inf')
    for i in range(len(a)):
        if a[i] in index:
            dist=i-index[a[i]]
            min_dict=min(min_dict,dist)
        index[a[i]]=i
    return min_dict if min_dict!=float('inf')else-1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = minimumDistances(a)

    fptr.write(str(result) + '\n')

    fptr.close()
