#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'separateNumbers' function below.
#
# The function accepts STRING s as parameter.
#

def separateNumbers(s):
    # Write your code here
    for i in range(1,len(s)//2+1):
        first=int(s[:i])
        current=first
        temp=str(first)
        while len(temp)<len(s):
            current+=1
            temp+=str(current)
        if temp==s:
            print(f"YES {first}")
            return
    print("NO")

if __name__ == '__main__':
    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        separateNumbers(s)
