#!/bin/python3

import math
import os
import random
import re
import sys
import string
#
# Complete the 'minimumNumber' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. STRING password
#

def minimumNumber(n, password):
    # Return the minimum number of characters to make the password strong
    min_val=0
    has_num=False
    has_lower=False
    has_upper=False
    has_special=False
    special_char="!@#$%^&*()-+"
    for i in password:
        if i.isdigit():
            has_num=True
        elif i.islower():
            has_lower=True
        elif i.isupper():
            has_upper=True
        elif i in special_char:
            has_special=True
    if not has_num:
        min_val+=1
    if not has_lower:
        min_val+=1
    if not has_upper:
        min_val+=1
    if not has_special:
        min_val+=1          
    return max(min_val,6-n)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    password = input()

    answer = minimumNumber(n, password)

    fptr.write(str(answer) + '\n')

    fptr.close()
